### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by RintaDev5792** [strawdynamics/pdportal#4]
**Is your feature request related to a problem? Please describe.**
I have no clue what I'm doing when I try to program with this

**Describe the solution you'd like**
Some form of documentation, even just a text file would be amazing, explaining just how to do anything with this.

**Describe alternatives you've considered**
DMing @paulstraw but I don't want to annoy him

**Comment by paulstraw** [comment]
@DethDefier have you looked at the examples here? https://github.com/strawdynamics/pdportal/tree/main/lua/examples

**Comment by RintaDev5792** [comment]
I have, I'm not great at understanding others' code

**Comment by paulstraw** [comment]
Doing some maintenance on this project, and I realized I should have pointed out the https://github.com/strawdynamics/pdportal/blob/main/lua/pdportal.lua file. I would still like to do some more in-depth documentation, but maybe that combined with the 01-simple example will be enough to get you pointed in the right direction.

If you have specific questions, please feel free to post them here. Understanding what someone naturally struggles with while getting started will help inform future docs.

**Comment by paulstraw** [comment]
I should also note that looking in your browser console on https://pdportal.net will give some instructions on how to enable a development screen, which can be used to fake a second Playdate by sending arbitrary commands over the connection. This is how I tested the simple sample and Net-tac-toe.

**Comment by paulstraw** [comment]
Hey @DethDefier, I've made quite a few updates to the documentation in the recently released 0.2.0. Please have a look at the various README.md files and let me know if this helps clarify things for you. Thanks!

**Comment by RintaDev5792** [comment]
I've looked at some of them and it makes a lot more sense now, ty! I will try messing around with it more! (Also this is completely unrelated but we've talked on discord I'm @rintadev)

**Comment by paulstraw** [comment]
Awesome, glad things make more sense. I'm going to go ahead and close this issue, but please feel free to open another one if you have more specific questions!
